### ISSUE TITLE
[Pkgs] Need to add in ability to use function as types

### ISSUE THREAD

**Issue by VoR0220** [monax/monax#1114]
Calls and ABI need to be updated to be able to handle function types. Furthermore, we can fancy this up by having the job be smart enough to decipher what function its looking for based on the address of the deploy job and the function name and arguments passed in. Something like this. 

```
job:
    call:
        function: someFunc
        data:
            - 1
            - 2
            - $deployJob.funcName(1,2,3)
```
