### ISSUE TITLE
[pkgs] abort jobs execution with error if invalid operators are used

### ISSUE THREAD

**Issue by j-h-scheufen** [monax/monax#1135]
Problem:
An `assert` job in EPM of the following example uses an invalid operator `neq` (correct: `ne`). The job logs as `Executing`, but there is no further output of the assertion and it proceeds with the next job.

Expectation: 
Using an invalid comparison operator should cause the job execution to fail with an error.

Jobs:
```
- name: note1EndorsedBefore
  job:
    query-contract:
      destination: $note1
      abi: PromissoryNote
      data: isEndorsed

- name: assertEndorsement1Before
  job:
    assert:
      key: $note1EndorsedBefore
      relation: neq
      val: "true"
```
Output:
```
Executing Job                                 note1EndorsedBefore
Return Value                                  true
Executing Job                                 assertEndorsement1Before
Executing Job                                 runEndorsement1
```
